minimum_pre_commit_version: 3.0.0
default_language_version:
    python: python3.12
repos:
    - repo: local
      hooks:
          - id: ruff check
            name: ruff check
            stages: [commit]
            language: system
            entry: poetry run ruff check
            types: [python]

          - id: ruff format
            name: ruff format
            stages: [commit]
            language: system
            entry: poetry run ruff format
            types: [python]

          - id: mypy
            name: mypy
            stages: [commit]
            language: system
            entry: poetry run mypy
            types: [python]
            pass_filenames: false
